name: Build Windows EXE

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:


      - uses: actions/checkout@v4


      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"



      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install yt-dlp pyinstaller pillow



      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
          powershell Expand-Archive ffmpeg.zip -DestinationPath ffmpeg




      - name: Extract ffmpeg.exe
        run: |
          $f = Get-ChildItem -Recurse -Filter ffmpeg.exe | Select-Object -First 1
          Copy-Item $f.FullName ./ffmpeg.exe -Force




      - name: Build EXE (FORCED OUTPUT NAME)
        run: pyinstaller --onefile --windowed --icon=icon.ico --add-binary "ffmpeg.exe;." --name down down.py


      - name: Generate update.json
        shell: pwsh
        run: |

          $hash = (
            Get-FileHash "dist/down.exe" -Algorithm SHA256
          ).Hash.ToLower()

          @{
            version = "2.6.9"
            sha256  = $hash
          } |
          ConvertTo-Json |
          Set-Content "dist/update.json" -Encoding UTF8

          Write-Host ""
          Write-Host "Generated update.json:"
          Write-Host ""

          Get-Content "dist/update.json"

          Write-Host ""


      - name: Verify build output
        run: dir dist


      - name: Upload artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: downloader-exe
          path: dist/*



      - name: Update 2.6.9 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 2.6.9
          files: |
            dist/down.exe
            dist/update.json
          overwrite_files: true
