name: Build Windows EXE

on:
  push:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install yt-dlp pyinstaller

      - name: Download ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
          powershell Expand-Archive ffmpeg.zip -DestinationPath ffmpeg

      - name: Rename ffmpeg for stable path
        run: |
          powershell -Command "Get-ChildItem -Recurse -Filter ffmpeg.exe | Select-Object -First 1 | Copy-Item -Destination ffmpeg.exe"

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed ^
            --icon=icon.ico ^
            --add-binary "ffmpeg.exe;." ^
            down.py

      - uses: actions/upload-artifact@v4
        with:
          name: downloader-exe
          path: dist/*
